### ISSUE TITLE
站点没法用了，不显示布局了，代码还能看

### ISSUE THREAD

**Issue by ivoidcat** [iamxcd/tkinter-helper#10]
https://www.pytk.net/tkinter-helper/#/
<img width="726" alt="image" src="https://user-images.githubusercontent.com/19281566/206630373-54ede5f0-7994-4d02-9aa4-f13ba3ee6f6d.png">
<img width="987" alt="image" src="https://user-images.githubusercontent.com/19281566/206630421-9d61fa82-442d-4022-a779-df7c43ec88b8.png">

**Comment by iamxcd** [comment]
把你的布局文件导出，再清空缓存试试。

**Comment by ivoidcat** [comment]
我新开了一个浏览器都不行

**Comment by iamxcd** [comment]
我这测试没有任何问题，发下控制台截图看看，看下有没有报错信息。
![image](https://user-images.githubusercontent.com/45652563/206700578-72ddb461-34c7-4e57-8856-c681eeb0de5e.png)

**Comment by ivoidcat** [comment]
<img width="1269" alt="image" src="https://user-images.githubusercontent.com/19281566/206704690-7cd2dcab-a09f-4c2e-af89-416b04de80d9.png">
新放进去的是没有问题得，只是之前的布局跟之前导出的再导入都不显示了

**Comment by iamxcd** [comment]
那应该是新加的功能，有些不兼容以前的版本。tk布局文件是base64编码的json字符串，你把最新的tk布局文件下载下来，与原先的对比看看，结合错误信息，看是缺失哪些字段补上，再编码导入试试。

**Comment by iamxcd** [comment]
如果东西比较多，建议将本项目下载下去，切换到之前的版本，在本地布局。目前还在更新功能，个人精力有限，兼容性问题暂处理不了。这些问题都是可以通过调整tk布局文件里面的json字段修复的，能恢复正常。

**Comment by iamxcd** [comment]
已经增加布局文件修复功能
![image](https://user-images.githubusercontent.com/45652563/206834082-d51c5f55-b4f8-4b64-b92c-3752561a1a95.png)
