### ISSUE TITLE
助手生成的title和按钮，都无法使用加载图片，是不支持还是我改错了

### ISSUE THREAD

**Issue by weinv** [iamxcd/tkinter-helper#12]
def __tk_label_logo(self,parent):
        img = Image.open("st.png")
        img = img.resize((100, 100))
        img = ImageTk.PhotoImage(img)
        btn = ttk.Button(parent, image=img).pack()
        return btn

**Comment by iamxcd** [comment]
函数执行后内部变量资源被释放的原因，解决方法参见：https://www.pytk.net/blog/1682473570.html
