### ISSUE TITLE
事件绑定功能

### ISSUE THREAD

**Issue by Jzhenli** [iamxcd/tkinter-helper#3]
如果能生成事件绑定模板就更好了，期待

**Comment by iamxcd** [comment]
后面会增加

**Comment by uc22** [comment]
# TODO 绑定点击事件或其他逻辑处理

菜鸟请教下，如何在此处优雅地绑定事件呢？

**Comment by iamxcd** [comment]
![image](https://user-images.githubusercontent.com/45652563/190954507-57d56583-3dce-4193-bbc6-9eb6f8731ffb.png)
事件绑定功能已更新

**Comment by uc22** [comment]
newbee!
