### ISSUE TITLE
frame容器内控件位置问题

### ISSUE THREAD

**Issue by uc22** [iamxcd/tkinter-helper#6]
控件放入Frame容器内后，控件位置发生偏移，无法所见即所得，麻烦大佬看看。

**Comment by iamxcd** [comment]
放个截图下 我这测 好像没问题

**Comment by uc22** [comment]
![1](https://user-images.githubusercontent.com/51921920/191216533-4717d474-6dc5-424b-b8ae-2a39b0ff20b8.png)
![2](https://user-images.githubusercontent.com/51921920/191216550-e5e3545b-036c-4fe9-b720-a26d82bce542.png)

**Comment by uc22** [comment]
1、网格是否可以调整为5px；
2、另外字体大小可否调整下，python中是偏小的。

**Comment by iamxcd** [comment]
小细节还有很多问题，我后面抽时间修复下

**Comment by iamxcd** [comment]
LabelFrame 的问题已经修复 。字体大小我调整了一些，看着大小差不多。布局时和最终展示的时候，渲染会有些不一致,，这里我是能接受，完全一致太耗费精力了，我给布局助手的定位是制作小工具，如果你对这块有需求欢迎提PR。
