### ISSUE TITLE
生成的事件绑定代码无法运行

### ISSUE THREAD

**Issue by Jzhenli** [iamxcd/tkinter-helper#7]
试了下事件绑定代码，貌似有问题。
![image](https://user-images.githubusercontent.com/42105688/191445594-45532c1c-aa67-4ae3-88d2-c2de5bbb527e.png)

生成的代码
![image](https://user-images.githubusercontent.com/42105688/191448937-673020c9-af43-4ef0-8b7b-a2251f933368.png)

运行时会提示事件绑定代码中的win未定义，建议模板按如下修改，左边是原始代码，后面是改动后的代码
![image](https://user-images.githubusercontent.com/42105688/191449094-1346ece7-3291-4031-a054-1e090cfe220d.png)

**Comment by iamxcd** [comment]
我这测试没问题。模板已经调整成类的形式了
