### ISSUE TITLE
组件视图希望能够优化一下

### ISSUE THREAD

**Issue by Wrong-pixel** [iamxcd/tkinter-helper#8]
最近试用了一下，确实挺好用的，但还是提一个小建议
当一个frame中嵌套另一个frame，同时还有很多组件时，选中一个组件就不太直观了，建议通过颜色显示选中的组件的父frame，比如：
<img width="222" alt="image" src="https://user-images.githubusercontent.com/43137902/195773539-e9aa4f6a-71b4-41f7-8a77-f90bb0b9b068.png">
这样在完成复杂界面的排版后也能快速定位组件的位置

**Comment by iamxcd** [comment]
有相关的计划，在页面左下角会增加个组件的树图，方便查看、切换选择的组件。
