### ISSUE TITLE
能否加入ttkbootstrap进行拖拽布局

### ISSUE THREAD

**Issue by carve-myself** [iamxcd/tkinter-helper#9]
https://github.com/israel-dryer/ttkbootstrap

**Comment by iamxcd** [comment]
暂不会加入。但当前项目的定位值制作小工具，基础的已经够用了，如果加上ttkbootstrap会增加很多工作量。如果想使用ttkbootstrap，在生成的代码里面将导入模块的语句替换成ttkbootstrap相关的就可以了。
